### ISSUE TITLE
Errata vs original wayback-machine-downloader, Sub-Directory Target, Spaces in Filenames, and Port Number in the Archive Address.

### ISSUE THREAD

**Issue by KarmaMechanic** [bitdruid/python-wayback-machine-downloader#1]
A couple of issues have cropped so far that have kept me from using this tool as I'd really like to:
1. When I input a target URL like, 
example.com/documents/ 
rather than pull everything in the target directory, in this case /documents/ (including the many sub-directories in that I'd like to get), instead it still just tries to pull the entire site at the root (example.com)

2. Also, the files that are saved end up with "%20" replacing the spaces in the original filenames which makes it a huge hassle if the website you're working with has thousands of files with spaces that would then need to be manually renamed back to their original names be fileable/sortable/non-duplicating vs earlier backups.

3. Also, some pages on Wayback Machine are backed up with a port number in the URL (for some reason) such as www.example.com:80 which kicks back the following error when otherwise running:
NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Archive\\www.example.com:80'

**Comment by bitdruid** [comment]
> A couple of issues have cropped so far that have kept me from using this tool as I'd really like to:
> 1. When I input a target URL like, 
> example.com/documents/ 
> rather than pull everything in the target directory, in this case /documents/ (including the many sub-directories in that I'd like to get), instead it still just tries to pull the entire site at the root (example.com)
> 
> 2. Also, the files that are saved end up with "%20" replacing the spaces in the original filenames which makes it a huge hassle if the website you're working with has thousands of files with spaces that would then need to be manually renamed back to their original names be fileable/sortable/non-duplicating vs earlier backups.
> 
> 3. Also, some pages on Wayback Machine are backed up with a port number in the URL (for some reason) such as www.example.com:80 which kicks back the following error when otherwise running:
> NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Archive\\www.example.com:80'
> 

2 and 3 i will have a look soon. for your first one - did you use current or full download?

**Comment by bitdruid** [comment]
fixed 2 and 3 with the new release. i also clarified the current path-structure in readme. have to overthink if it makes sense to use the requested url/path as "root" for all timestamps. my intention on the path is, that there is always the root of the query as startpoint inside the output containing then the queried path.
