### ISSUE TITLE
Adding a tool name to UserAgent

### ISSUE THREAD

**Issue by Ghost-chu** [bitdruid/python-wayback-machine-downloader#11]
Add the program name to the User-Agent to allow archive.org to recognize it.

**Comment by bitdruid** [comment]
> Add the program name to the User-Agent to allow archive.org to recognize it.

how would you rewrite the user-agent in this case?

**Comment by Ghost-chu** [comment]
> > Add the program name to the User-Agent to allow archive.org to recognize it.
> 
> how would you rewrite the user-agent in this case?

I would like to use `bitdruid/python-wayback-machine-downloader (1.1.0)`, maybe the user can change it too.

Using a browser UA doesn't seem to be a good option, it might confuse archive.org.

**Comment by Ghost-chu** [comment]
Even though it's not very standard, it seems to suffice:

more standard:

`bitdruid-python-wayback-machine-downloader/1.1.0`

**Comment by bitdruid** [comment]
> Even though it's not very standard, it seems to suffice:
> 
> more standard but looks a little bit weird:
> 
> `bitdruid-python-wayback-machine-downloader/1.1.0`

sounds okay to me. but do you have any sources for this approach? like if other tools doing so

**Comment by Ghost-chu** [comment]
> > Even though it's not very standard, it seems to suffice:
> > more standard but looks a little bit weird:
> > `bitdruid-python-wayback-machine-downloader/1.1.0`
> 
> sounds okay to me. but do you have any sources for this approach? like if other tools doing so

Without a specific source, UA usually consists of `ProgramName/Version (Comment)`, but I'm not sure what the real name of this Program is, so I went with `username-repository/version`

**Comment by bitdruid** [comment]
fixed with release :)
