### ISSUE TITLE
Is skipset was removed from 1.2.0?

### ISSUE THREAD

**Issue by Ghost-chu** [bitdruid/python-wayback-machine-downloader#12]
I noticed skipset stuff was commented out from source code.

Also could you catch the `ConnectionRefusedError` and `TimeoutError` in `download()`?

**Comment by bitdruid** [comment]
skip uses now the csv instead of an extra file. thats why skip_write was commented out :)

**Comment by bitdruid** [comment]
> I noticed skipset stuff was commented out from source code.
> 
> Also could you catch the `ConnectionRefusedError` and `TimeoutError` in `download()`?

this errors should already been catched. have you got one unhandled?

**Comment by Ghost-chu** [comment]
> > I noticed skipset stuff was commented out from source code.
> > Also could you catch the `ConnectionRefusedError` and `TimeoutError` in `download()`?
> 
> this errors should already been catched. have you got one unhandled?

sry, I mean ConnectionResetError and TimeoutError.
