### ISSUE TITLE
Error downloading archive

### ISSUE THREAD

**Issue by grigzy28** [bitdruid/python-wayback-machine-downloader#14]
**Describe**
"crashes" during downloads, doesn't produce error or any debug information

**Snapshot to reproduce**
http://wuarchive.wustl.edu/pub/

**Command to reproduce**
Two commands

initial command:
waybackup -d --csv -u http://wuarchive.wustl.edu/pub/ -o .\test3 -f --workers 3 --verbosity progress

second command(produced error log and trace callbacks):
waybackup -d --csv -u http://wuarchive.wustl.edu/pub/ -o .\test3 -f --workers 3 --verbosity progress --skip

**Terminal output**

**Additional context**

Potentially could the path be too long on some of them?  Just had that thought.

attached the csv and the error log.

[waybackup_error.log](https://github.com/user-attachments/files/15946618/waybackup_error.log)
[waybackup_http.wuarchive.wustl.edu.pub.csv](https://github.com/user-attachments/files/15946619/waybackup_http.wuarchive.wustl.edu.pub.csv)

**Comment by bitdruid** [comment]
So your csv was in place @ .\test3 and the second command (which produced the log) crashed immediately?

**Comment by grigzy28** [comment]
Also to note.  I had some previous runs (test1 and test2) where it would run thru a bit but then error out when the internet would go out.  Would fail with getaddr failures and abort out, which is why I tried the CSV file option.

Is there possibly any way to help with that kind of situation?  Should I just make a new feature request for this?

**Comment by grigzy28** [comment]
Another issue with this particular archive is that it would just stop mid-way thru and control-c doesn't work to abort it.  Only way to terminate it is with ending the task in task manager.  (waybackup.exe)

**Comment by grigzy28** [comment]
One other note, this is Python 3.12 as you can see in the path, but it is the x64 version.  If that helps any.

**Comment by bitdruid** [comment]
have you used version 1.2.3 from pip or the main branch manually?

i was trying to reproduce the error on linux, downloaded ~30k snapshots without an issue. so in the first run i increased the output of the error log and changed some file-exist checks.

i will try this on windows assoon as i have access to my vms again.

if you want you can try out the branch i created for this issue. maybe the increased log-output helps to investigate

**Comment by grigzy28** [comment]
It is 1.2.3 pip installed branch.

I can try it on linux as well to see.

**Comment by bitdruid** [comment]
> It is 1.2.3 pip installed branch.
> 
> I can try it on linux as well to see.

did you use windows or linux when the error occured?

**Comment by grigzy28** [comment]
I was on windows.

**Comment by grigzy28** [comment]
Just an FYI, the test build that you made did finish without stopping halfway thru like it had been with the 1.2.3

Going to re-download it again the other way that I wanted to grab it as well (-f instead of -c)

**Comment by bitdruid** [comment]
oh nice to hear - on your windows machine? i implemented to skip patgs >255 chars today for win

not tge best solution but no other option here without changeing the registry. i will update the readme for this 🤔

**Comment by grigzy28** [comment]
Yes, it was on windows.  I guess I will have to try and run it on linux since the paths might be what caused the issue, maybe you can output in the debug log file that there was a path error and skipped file?  Would be helpful to go and manually grab files, if need be.

**Comment by bitdruid** [comment]
you are right. maybe a info in the json instead of the filepath (and also in the csv then)

**Comment by grigzy28** [comment]
This is what happened when I did the -f

I don't know why it just stopped at the 28678, there was no error log generated either. 
[waybackup_http.wuarchive.wustl.edu.pub.csv](https://github.com/user-attachments/files/15995998/waybackup_http.wuarchive.wustl.edu.pub.csv)

C:\Users\Shawn\AppData\Roaming\Python\Python312\Scripts>waybackup -d --csv -u http://wuarchive.wustl.edu/pub/ -o .\test6 -f --workers 3 --verbosity progress --skip
Downloading:   4%|██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░| 28678/669820 [5:32:28<123:53:10,  1.44 snapshot/s]

C:\Users\Shawn\AppData\Roaming\Python\Python312\Scripts>waybackup -d --csv -u http://wuarchive.wustl.edu/pub/ -o .\test6 -f --workers 3 --verbosity progress --skip
-------------------------
!-- Exception: Could not read CSV-file
!-- File: ..\site-packages\pywaybackup\archive.py
!-- Function: csv_read
!-- Line: 407
!-- Segment: return [row[2] for row in csv_reader]
!-- Description: list index out of range
-------------------------
Exception log: .\test6\waybackup_error.log
-------------------------
Full traceback:
Traceback (most recent call last):
  File "..\site-packages\pywaybackup\archive.py", line 407, in csv_read
    return [row[2] for row in csv_reader]
            ~~~^^^
IndexError: list index out of range


-------------------------
!-- Exception: Could not open CSV-file
!-- File: ..\site-packages\pywaybackup\archive.py
!-- Function: skip_open
!-- Line: 429
!-- Segment: skipset = set(csv_read(csv_file))
!-- Description: 'NoneType' object is not iterable
-------------------------
Exception log: .\test6\waybackup_error.log
-------------------------
Full traceback:
Traceback (most recent call last):
  File "..\site-packages\pywaybackup\archive.py", line 429, in skip_open
    skipset = set(csv_read(csv_file))
              ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable



Interrupted by user

**Comment by bitdruid** [comment]
do you have the error-log?

**Comment by grigzy28** [comment]
There was no error log generated for the first run, here is the second run
[waybackup_error.log](https://github.com/user-attachments/files/15996853/waybackup_error.log)

**Comment by bitdruid** [comment]
you could also download with standard output (remove verbosity) and you may see why the download stops. it could be a refused connection for example

**Comment by grigzy28** [comment]
This is what I get after upgrading pip install pywaybackup to the 1.2.4 that you released.  That previous run was still the build you had made when we were testing it previously.

C:\Users\Shawn\AppData\Roaming\Python\Python312\Scripts>waybackup -d --csv -u http://wuarchive.wustl.edu/pub/ -o .\test7 -f --workers 3 --verbosity progress --skip
-------------------------
!-- Exception: Could not save CSV-file
!-- File: ..\site-packages\pywaybackup\archive.py
!-- Function: csv_close
!-- Line: 397
!-- Segment: if snapshot["response"] is not False: # only append handled snapshots
!-- Description: 'response'
-------------------------
Exception log: .\test7\waybackup_error.log
-------------------------
Full traceback:
Traceback (most recent call last):
  File "..\site-packages\pywaybackup\main.py", line 46, in main
    archive.download_list(args.output, args.retry, args.no_redirect, args.workers, skipset)
  File "..\site-packages\pywaybackup\archive.py", line 162, in download_list
    vb.write("\nDownloading snapshots...", progress=0)
  File "..\site-packages\pywaybackup\Verbosity.py", line 41, in write
    maxval = sc.count_list()
             ^^^^^^^^^^^^^
AttributeError: type object 'SnapshotCollection' has no attribute 'count_list'. Did you mean: 'create_list'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "..\site-packages\pywaybackup\archive.py", line 397, in csv_close
    if snapshot["response"] is not False: # only append handled snapshots
       ~~~~~~~~^^^^^^^^^^^^
KeyError: 'response'


-------------------------
!-- Exception: UNCAUGHT EXCEPTION
!-- File: ..\site-packages\pywaybackup\Verbosity.py
!-- Function: write
!-- Line: 41
!-- Segment: maxval = sc.count_list()
!-- Description: type object 'SnapshotCollection' has no attribute 'count_list'
-------------------------
Exception log: .\test7\waybackup_error.log
-------------------------
Full traceback:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "waybackup.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "..\site-packages\pywaybackup\main.py", line 46, in main
    archive.download_list(args.output, args.retry, args.no_redirect, args.workers, skipset)
  File "..\site-packages\pywaybackup\archive.py", line 162, in download_list
    vb.write("\nDownloading snapshots...", progress=0)
  File "..\site-packages\pywaybackup\Verbosity.py", line 41, in write
    maxval = sc.count_list()
             ^^^^^^^^^^^^^
Attribut
[waybackup_http.wuarchive.wustl.edu.pub.csv](https://github.com/user-attachments/files/15997203/waybackup_http.wuarchive.wustl.edu.pub.csv)
[waybackup_error.log](https://github.com/user-attachments/files/15997204/waybackup_error.log)
eError: type object 'SnapshotCollection' has no attribute 'count_list'. Did you mean: 'create_list'?

**Comment by grigzy28** [comment]
the above command was run with an empty directory, I change the test folder numbers between different runs ( -c vs -f ) and versions

**Comment by bitdruid** [comment]
let me check that out later. csv should not be "None" type and properly created if missing🤔 it seems to be windows causing that pain

**Comment by grigzy28** [comment]
Got a run to finish thru no progress, however when trying to run the same command again I get an error on the CSV file that was created with the first run.

Thanks

C:\Users\Shawn\AppData\Roaming\Python\Python312\Scripts>waybackup -d --csv -u http://wuarchive.wustl.edu/pub/ -o .\test9 -f --workers 3 --skip
-------------------------
!-- Exception: Could not read CSV-file
!-- File: ..\site-packages\pywaybackup\archive.py
!-- Function: csv_read
!-- Line: 409
!-- Segment: return [row[2] for row in csv_reader]
!-- Description: list index out of range
-------------------------
Exception log: .\test9\waybackup_error.log
-------------------------
Full traceback:
Traceback (most recent call last):
  File "..\site-packages\pywaybackup\archive.py", line 409, in csv_read
    return [row[2] for row in csv_reader]
            ~~~^^^
IndexError: list index out of range


-------------------------
!-- Exception: Could not open CSV-file
!-- File: ..\site-packages\pywaybackup\archive.py
!-- Function: skip_open
!-- Line: 431
!-- Segment: skipset = set(csv_read(csv_file))
!-- Description: 'NoneType' object is not iterable
-------------------------
Exception log: .\test9\waybackup_error.log
-------------------------
Full traceback:
Traceback (most recent call last):
  File "..\site-packages\pywaybackup\archive.py", line 431, in skip_open
    skipset = set(csv_read(csv_file))
              ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable


[Desktop.zip](https://github.com/user-attachments/files/16029909/Desktop.zip)

**Comment by bitdruid** [comment]
im back home on sunday. there i can check that out on my win vm. hopefully identifying the problem

**Comment by grigzy28** [comment]
Ok, thanks.  Just trying to help out squashing any bugs... :)

**Comment by bitdruid** [comment]
> Hi! First of all: Thanks for building this!
> 
> I came upon a related issue. It might be somethin new, though. Let me know if I should open a new issue.
> 
> I'm on a VM running Ubuntu 22.04.4 LTS and waybackup 1.3.2, installed via pip in a virtual env - and having issues with saving an archive list to csv.
> 
> The following command doesn't work properly:
> 
> waybackup -u example.com/2/1 -f -l --csv /home/USER/Downloads/
> 
> It writes a file to directory with headers only, but no converted json output.
> 
> I get the following cmd output:
> 
> > Querying snapshots...
> > ---> example.com/2/1/*
> > -----> 5 snapshots to utilize
> > [{'digest': 'JI6OR3QR4CI526JD6TMMNZNV4QPMPQCH',
> > 'id': 0,
> > 'mimetype': 'text/html',
> > 'status': '404',
> > 'timestamp': '20220905021401',
> > 'url': 'http://example.com/2/1'},
> > {'digest': 'B2LTWWPUOYAH7UIPQ7ZUPQ4VMBSVC36A',
> > 'id': 1,
> > 'mimetype': 'text/html',
> > 'status': '404',
> > 'timestamp': '20181105042145',
> > 'url': 'http://example.com/2/1'},
> > {'digest': 'B2LTWWPUOYAH7UIPQ7ZUPQ4VMBSVC36A',
> > 'id': 2,
> > 'mimetype': 'warc/revisit',
> > 'status': '-',
> > 'timestamp': '20140613215919',
> > 'url': 'http://example.com/2/1'},
> > {'digest': '3I42H3S6NNFQ2MSVX7XZKYAYSCX5QBYJ',
> > 'id': 3,
> > 'mimetype': 'unk',
> > 'status': '302',
> > 'timestamp': '20130611231905',
> > 'url': 'http://example.com/2/1'},
> > {'digest': '3I42H3S6NNFQ2MSVX7XZKYAYSCX5QBYJ',
> > 'id': 4,
> > 'mimetype': 'unk',
> > 'status': '302',
> > 'timestamp': '20130611231905',
> > 'url': 'http://example.com/2/1'}]
> > ## -----> 5 snapshots listed
> > !-- Exception: Could not save CSV-file
> > !-- File: waybackdownloaderEnvironment/lib/python3.10/site-packages/pywaybackup/archive.py
> > !-- Function: csv_close
> > !-- Line: 408
> > !-- Segment: if snapshot["response"] is not False: # only append handled snapshots
> > !-- Description: 'response'
> 
> However, if I download all Snapshots and also save to csv, it works:
> 
> waybackup -u example.com/2/1 -f --csv
> 
> This results in a folder with all snapshots and an additional csv file, looking like this:
> 
> ![screenshot](https://private-user-images.githubusercontent.com/151626374/353399613-d36b72ed-eeb6-459d-aeaa-0c89212a9fc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNjg5MTMsIm5iZiI6MTcyMjM2ODYxMywicGF0aCI6Ii8xNTE2MjYzNzQvMzUzMzk5NjEzLWQzNmI3MmVkLWVlYjYtNDU5ZC1hZWFhLTBjODkyMTJhOWZjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMFQxOTQzMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OThiODVlZTM0NDIyZDg2M2ZjZTZhMzg2ZmVmMWQ5ZGU5NDQ4ZDRjNTRlZGZjN2MxZDBkNWNiY2Y4NzhlYWEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.92ZILa3h3pykLf9RVs5WNqK9LDFWIaLx8rfSx9QBEDU)
> 
> Any suggestions?

heyhey :) i wrote a fix for your issue. it should now work as intended on version 1.4.1

**Comment by Tiptop4792** [comment]
Awesome, thanks! Works great!
