### ISSUE TITLE
[Feature Request] Configurable time delay option between worker requests from server

### ISSUE THREAD

**Issue by grigzy28** [bitdruid/python-wayback-machine-downloader#17]
**Describe**
Include an optional configurable delay/pause between worker requests from servers that are being downloaded from.

**Snapshot to reproduce**
n/a

**Command to reproduce**
n/a

**Terminal output**
```
n/a
```

**Additional context**
n/a

**Comment by bitdruid** [comment]
what do you mean? a delay between each snapshot? what benefit would there be from that?

**Comment by grigzy28** [comment]
I mean a small configurable/optional delay, say 1 or 2 seconds between each worker http/https request, for example.

I had an issue where I had 3 workers going against archive.org and it was considered a bot net attack.  I got a notice from my ISP about it.  Now maybe only 1 worker would not be considered, but not sure.

**Comment by bitdruid** [comment]
hm seems unusual because the http.client connection is kept alive during downloads for each worker. there are just new requests with the same connection. but seems not a big deal to implement that. i will add it within the next release 👍🏻
