### ISSUE TITLE
Unable to create a directory with the : character

### ISSUE THREAD

**Issue by roscopc88** [bitdruid/python-wayback-machine-downloader#2]
It tries to create a (win10) directory with an invalid character, like **example.com:80**

NotADirectoryError: [WinError 267] The directory name is invalid: 'c:\archive\www.example.com:80'

Therefore in my case it skipped all 1500 files I was trying to download.

**Comment by bitdruid** [comment]
> It tries to create a (win10) directory with an invalid character, like **example.com:80**
> 
> NotADirectoryError: [WinError 267] The directory name is invalid: 'c:\archive\www.example.com:80'
> 
> Therefore in my case it skipped all 1500 files I was trying to download.
> 

i will check that out soon. im only on linux and had not an eye on windows compatibility

**Comment by bitdruid** [comment]
> It tries to create a (win10) directory with an invalid character, like **example.com:80**
> 
> NotADirectoryError: [WinError 267] The directory name is invalid: 'c:\archive\www.example.com:80'
> 
> Therefore in my case it skipped all 1500 files I was trying to download.

could you provide an example snapshot for this to debug? tried a bunch of domains but couldn't find a representative example which ends with a port. however i think a simple change will do it anyway.

**Comment by roscopc88** [comment]
In earlier years, such as 2006, 2007 etc. the web archive has added a URL extension (:80). That is why it is useful to use the --end [date] option. Newer archived websites don't have that anymore.

> C:\python-wayback-machine-downloader-1.0.1>waybackup -u glitnir.is -f --end 20071231
> 
> Querying snapshots...
> -----> 30859 snapshots found
> 
> Downloading snapshots...
> Exception in thread Thread-1 (download_loop):
> Traceback (most recent call last):
>   File "C:\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
>     self.run()
>   File "C:\Python312\Lib\threading.py", line 1010, in run
>     self._target(*self._args, **self._kwargs)
>   File "C:\Python312\Lib\site-packages\pywaybackup\archive.py", line 151, in download_loop
>     download_status = download(output, snapshot, connection, status, no_redirect)
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Python312\Lib\site-packages\pywaybackup\archive.py", line 204, in download
>     os.makedirs(os.path.dirname(download_file), exist_ok=True)
>   File "<frozen os>", line 215, in makedirs
>   File "<frozen os>", line 215, in makedirs
>   File "<frozen os>", line 215, in makedirs
>   [Previous line repeated 1 more time]
>   File "<frozen os>", line 225, in makedirs
> NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\python-wayback-machine-downloader-1.0.1\\waybackup_snapshots\\www.glitnir.is:80'
> 
> Files downloaded: 1
> Files missing: 30858

**Comment by bitdruid** [comment]
thanks ok i see - that should be a simple change. will be fixed soon. i'm currently overthinking the best directory-structure for --full download. will merge everything when that's done
