### ISSUE TITLE
When a worker crashes, the batch it was processing cannot be taken over by other workers

### ISSUE THREAD

**Issue by Ghost-chu** [bitdruid/python-wayback-machine-downloader#9]
The current program splits the SNAPSHOT_COLLECTION into multiple batches in advance and submits them to different workers.

However, once the corresponding worker exits due to an exception, its batch cannot be processed by other workers unless the program is restarted (and causes the same result again)

I suggest rewriting it to share the same FIFO queue, which reduces memory consumption and allows other workers to continue working on unfinished work after one worker.

**Comment by bitdruid** [comment]
did minor changes to implement a queue
